### ISSUE TITLE
Product name doesn't comply with Apple Conventions

### ISSUE THREAD

**Issue by mdestagnol** [giladno/UICoreTextView#1]
This control looks very promising! Thanks for sharing your work!
But you should change your product name, "UI" prefix is reserved for Apple classes (cf. http://developer.apple.com/library/ios/#documentation/cocoa/conceptual/ProgrammingWithObjectiveC/Conventions/Conventions.html )

**Comment by giladno** [comment]
Thank you very much for the link, I wasn't aware of it. I'll rename the classes soon.

**Comment by mdestagnol** [comment]
You're welcome! :)

Martin

**Comment by giladno** [comment]
UI prefixed removed (https://github.com/giladno/UICoreTextView/commit/4ceff92ffb0e97b4e9c1a6548304cbf506d6b649)
