### ISSUE TITLE
Custom Fonts are not working

### ISSUE THREAD

**Issue by jinnajmal** [giladno/UICoreTextView#2]
i tried it with some custom Arabic fonts and its showing only device default font.

**Comment by giladno** [comment]
Could you please provide a sample project? Do you bundle those fonts with your project?

**Comment by jinnajmal** [comment]
I have performed the following changes into your provided Sample Code:
- Add the Font into application bundle
- add the custom font entry into application plist file 
  noorehira.ttf
- then added some Arabic Text into your sample html file 
  <span font='noorehira'>ذَٰلِكَ الْكِتَابُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًى لِلْمُتَّقِينَ</span>

but its not showing this custom font. its showing this Arabic text into Apple's default font.

https://dl.dropbox.com/u/6137862/noorehira.ttf

**Comment by giladno** [comment]
I've updated the sample project to show how to use a custom font (https://github.com/giladno/UICoreTextView/commit/b3b647d4140cfcf95189be0c8b5f7ad149ab240e)
